[directories]
rawdir = "/data2/LSC/DATA/RUN14/000099/"
triggerdir = "/data/users/azanelli/octopus_work/CROSS/RUN000099/Trigger/"

[runConfig]
filenamePrefix = ["20251219T231206"]
runNumber = ["000099"]

[settings]
rawType = "Cupid"
runType = "trigger"
draw = false
noiseTriggerPeriod = 5
overwrite = true
verbosity = 5
applyFilter = false

[channels.heat]
list = [1]
waveformtype = "continuous"

[trigger.linearinterpolation.heat]
NRMSList = [3.2]
NAboveList = [5]
DeadTimeList = [0.12]
ReadFromTxt = "/data/users/azanelli/Octopus/detectormaps/ThresholdsCROSS.txt"
BufferLengthList = [0.1]
NoisePeriodList = [10.0123456]
Draw = false
