[directories]
rawdir = "/data2/LSC/DATA/RUN14/000096/"
triggerdir = "/data/users/ploaiza/Octopus/Octopus_work/RUN000096/Trigger/"

[runConfig]
filenamePrefix = ["20251215T103142"]
runNumber = ["000096"]

[settings]
rawType = "Cupid"
runType = "trigger"
draw = false
noiseTriggerPeriod = 5
overwrite = true
verbosity = 5
applyFilter = false

[channels.heat]
list = [2]
waveformtype = "continuous"
PulserLabel = "LED"
IsPulser = true

[trigger.derivative.heat]
UseFixedThreshold = [true]
FixedThrList = [1.2]
BufferLengthList = [0.1]
NoisePeriodList = [10000000.0]
Draw = false
