[directories]
rawdir = "/data2/LSC/DATA/RUN14/000106/"
triggerdir = "/data/users/azanelli/octopus_work/CROSS/RUN000106/Trigger/"

[runConfig]
filenamePrefix = ["20260116T143650"]
runNumber = ["000106"]

[settings]
rawType = "Cupid"
runType = "trigger"
draw = false
noiseTriggerPeriod = 5
overwrite = true
verbosity = 5
applyFilter = false

[channels.heat]
list = [27]
waveformtype = "continuous"

[trigger.linearinterpolation.heat]
NRMSList = [3.2]
NAboveList = [5]
DeadTimeList = [0.12]
ReadFromTxt = "/data/users/azanelli/Octopus/detectormaps/ThresholdsCROSS.txt"
BufferLengthList = [0.1]
NoisePeriodList = [10.0123456]
Draw = false
